# End-User License Agreement (EULA)

**Package:** gamerebellion-unreal-sdk (Unreal Engine)
**Company:** GameRebellion Inc.
**Version:** 1.0.0
**Last updated:** August 17, 2026

> This agreement governs your use of the GameRebellion SDK in every form in which it is distributed — including the **Unity package** (`com.gamerebellion.sdk`) and the **Unreal Engine plugin** (`gamerebellion-unreal-sdk`) — referred to throughout as "the SDK".
>
> By downloading, installing, or using the SDK, you agree to be bound by the terms of this agreement and GameRebellion's [Terms of Service](https://gamerebellion.com/terms-of-service). If you do not accept these terms, you must not use the SDK.

---

## 1. Usage restrictions

Use of the SDK is subject to the following conditions:

- **Valid account required.** The SDK may only be used in conjunction with a valid, active GameRebellion account. Access to the SDK's features is contingent on maintaining an authorized account in good standing.
- **No reverse engineering.** You may not decompile, disassemble, reverse-engineer, or otherwise attempt to derive the source code, underlying algorithms, or structure of the SDK's compiled binaries. Where the SDK includes source files so that your engine or toolchain can compile them (for example the Unreal plugin's C++ sources), those files are provided solely for that purpose; their inclusion does not grant any right to derive or reconstruct the GameRebellion core.
- **No redistribution.** You may not redistribute, resell, sublicense, or share the SDK outside of its intended use as a Unity package or Unreal Engine plugin integration in your own project. Redistribution through asset stores, marketplaces, package registries, repositories, or any other channel is strictly prohibited.

---

## 2. Data collection & telemetry

By using the SDK, you acknowledge and agree to the following:

- **Data collected.** The SDK may collect technical and usage data including, but not limited to: device identifiers, session metrics, in-game events, performance diagnostics, and integration logs.
- **Data transmission.** All collected data is transmitted to and processed by the GameRebellion platform in accordance with GameRebellion's [Privacy Policy](https://gamerebellion.com/privacy-policy).
- **Developer responsibility.** You, as the developer integrating the SDK into your product, are solely responsible for obtaining all necessary consents from your end users as required by applicable data protection laws, including but not limited to the General Data Protection Regulation (GDPR), the California Consumer Privacy Act (CCPA), and any other relevant privacy legislation in your jurisdiction. GameRebellion shall not be held liable for your failure to comply with such obligations.

---

## 3. Ownership

- **SDK ownership.** The GameRebellion SDK — including the `com.gamerebellion.sdk` Unity package, the `gamerebellion-unreal-sdk` Unreal Engine plugin, and all compiled binaries, sources, assets, APIs, and documentation distributed with either — is and remains the exclusive intellectual property of GameRebellion Inc. This agreement does not transfer any ownership rights to you.
- **Your game & data.** You retain full ownership of your game, application, and the data generated by your end users. GameRebellion is granted a limited, non-exclusive license solely to process that data for the purpose of providing and improving the GameRebellion platform services, as described in GameRebellion's Privacy Policy.

---

## 4. Termination

- **Revocation for abuse.** GameRebellion reserves the right to revoke your license to use the SDK at any time, with or without notice, if you are found to be in violation of any term of this agreement or if your use is deemed abusive, fraudulent, or harmful to GameRebellion or its users.
- **Dependency on backend access.** The SDK requires an active connection to the GameRebellion backend to function. In the event that your account is suspended, terminated, or otherwise loses authorization, the SDK will cease to operate. No refund or compensation is owed in such circumstances.
- **Effect of termination.** Upon termination, you must immediately cease all use of the SDK and remove it from your projects and systems.

---

## 5. Disclaimer of warranties

The SDK is provided **"as is"**, without warranty of any kind, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement. GameRebellion does not warrant that the SDK will be uninterrupted, error-free, or free of harmful components, or that it will build, compile, or operate against any particular version or custom build of Unity or Unreal Engine.

---

## 6. Limitation of liability

To the maximum extent permitted by applicable law, GameRebellion Inc. shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of or inability to use the SDK, even if advised of the possibility of such damages.

---

## 7. Governing law

This agreement is governed by the laws of the Province of Quebec, Canada, without regard to its conflict of law provisions. Any dispute arising under this agreement shall be subject to the exclusive jurisdiction of the competent courts of Montreal, Quebec.

---

*Unity is a trademark of Unity Technologies. Unreal Engine is a trademark of Epic Games, Inc. GameRebellion is not affiliated with or endorsed by either.*

*Copyright (c) 2026 GameRebellion Inc. - All rights reserved.*
